/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as TabuladoresRouteImport } from './routes/tabuladores'
import { Route as DocIdRouteImport } from './routes/doc.$id'
import { Route as EntidadSlugRouteImport } from './routes/entidad.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const TabuladoresRoute = TabuladoresRouteImport.update({
  id: '/tabuladores',
  path: '/tabuladores',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntidadSlugRoute = EntidadSlugRouteImport.update({
  id: '/entidad/$slug',
  path: '/entidad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/corpus': typeof CorpusRoute
  '/guardados': typeof GuardadosRoute
  '/tabuladores': typeof TabuladoresRoute
  '/doc/$id': typeof DocIdRoute
  '/entidad/$slug': typeof EntidadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/corpus': typeof CorpusRoute
  '/guardados': typeof GuardadosRoute
  '/tabuladores': typeof TabuladoresRoute
  '/doc/$id': typeof DocIdRoute
  '/entidad/$slug': typeof EntidadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/corpus': typeof CorpusRoute
  '/guardados': typeof GuardadosRoute
  '/tabuladores': typeof TabuladoresRoute
  '/doc/$id': typeof DocIdRoute
  '/entidad/$slug': typeof EntidadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/corpus'
    | '/guardados'
    | '/tabuladores'
    | '/doc/$id'
    | '/entidad/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/corpus'
    | '/guardados'
    | '/tabuladores'
    | '/doc/$id'
    | '/entidad/$slug'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/corpus'
    | '/guardados'
    | '/tabuladores'
    | '/doc/$id'
    | '/entidad/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CorpusRoute: typeof CorpusRoute
  GuardadosRoute: typeof GuardadosRoute
  TabuladoresRoute: typeof TabuladoresRoute
  DocIdRoute: typeof DocIdRoute
  EntidadSlugRoute: typeof EntidadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabuladores': {
      id: '/tabuladores'
      path: '/tabuladores'
      fullPath: '/tabuladores'
      preLoaderRoute: typeof TabuladoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entidad/$slug': {
      id: '/entidad/$slug'
      path: '/entidad/$slug'
      fullPath: '/entidad/$slug'
      preLoaderRoute: typeof EntidadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CorpusRoute: CorpusRoute,
  GuardadosRoute: GuardadosRoute,
  TabuladoresRoute: TabuladoresRoute,
  DocIdRoute: DocIdRoute,
  EntidadSlugRoute: EntidadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
